/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OlaJNI */

#ifndef _Included_OlaJNI
#define _Included_OlaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OlaJNI
 * Method:    olaMundo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_OlaJNI_olaMundo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
